name: appscrip_live_stream_component_example
description: Demonstrates how to use the appscrip_live_stream_component plugin.

publish_to: "none"
version: 1.0.2
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  appscrip_live_stream_component:
    path: ../
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  http: ^1.2.1
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+1
  in_app_purchase_storekit: ^0.3.17
  package_info_plus: ^8.0.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
 
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/gifts/
  - assets/icon/
